### DISCUSSION TITLE
IFTTT+Wyze Color Bulbs

### DISCUSSION THREAD

**Discussion by amitvaria** [SecKatie/ha-wyzeapi#132] [Show and tell]
By configuring [the IFTTT integration](https://www.home-assistant.io/integrations/ifttt/), I wrote up a simple automation that changes the color of the bulbs in the office when DoorDash is arriving.

My condition in the IFTTT applet is if my phone gets a notification from the DoorDash app that contains the word "approaching", then issue a webhook to my HA. You will need to be able to access your HA from the public internet so something like [DuckDNS](https://www.home-assistant.io/integrations/duckdns/) or [Home Assistant Cloud](https://www.home-assistant.io/cloud/) configured.

Once you get the apparatus setup, you can consider other interesting solutions like: change values when a Ring camera detects motion; you receive a SMS with specific words; etc.

```
alias: DoorDashArriving
description: ''
trigger:
  - platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: doordash_arriving
condition: []
action:
  - service: scene.create
    data:
      scene_id: dd_before
      snapshot_entities:
        - light.amit_office_1
        - light.amit_office_2
        - light.amit_office_3
  - service: light.turn_on
    data:
      color_name: darkgreen
    target:
      entity_id:
        - light.amit_office_1
        - light.amit_office_2
        - light.amit_office_3
  - delay: '00:00:04'
  - service: scene.turn_on
    data:
      entity_id: scene.dd_before
mode: single
```
