### DISCUSSION TITLE
Wyze Color Bulbs - Transitions

### DISCUSSION THREAD

**Discussion by jangerbauer** [SecKatie/ha-wyzeapi#200] [Q&A] [answered]
Hello.  I am using WYZE color bulbs with my HA automation and things are working quite nicely.

My question is: Does this integration support "transitions" -- i.e. can I use automation to slowly dim / brighten my lights over time? 

Here is my configuration:

```
alias: Lights on at sunset
description: ''
trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
condition: []
action:
  - service: scene.turn_on
    target:
      entity_id: scene.lights_on
    data:
      transition: 30
```

I have tried setting this up and the functionality doesn't seem to exist.  I'm happy to provide logging if that would help, but wanted to first see if this was supposed to be working or not.

Thanks.
