### DISCUSSION TITLE
Lock Battery Status

### DISCUSSION THREAD

**Discussion by hickerad** [SecKatie/ha-wyzeapi#248] [Q&A] [answered]
Good morning all! I found this project last night during my entire rebuild of my HA instance! I love that I can get to the bulbs and locks directly from HA now. I used to control the bulbs though HA via an IFTTT integration and input booleans. It was really messy and took a long time for a response to come through. 

Quick question, I looked through all of the discussion and didn't see it mentioned and/or asked, are there any plans to capture battery levels from the locks? 

Thanks for all of the hard work!

**Comment by JoeSchubert** [comment, marked as answer]
@hickerad It's been implemented in the latest beta (may be in stable by now).

**Reply by hickerad** [reply]
I saw that earlier today! Going to upgrade to the beta tomorrow. Thanks!

**Reply by kdoh82** [reply]
You might also want to create a custom sensor from the 'lock battery' attribute with a custom device class set to battery that way when you add it to your lovelace dashboard it will automatically show up as a percentage and update the icon based on the value. 

Here's the config I used to create the sensor:

```
# Custom Front Door Lock Battery Percentage Sensor from Wyze Lock Attribute - 'lock battery'
  - platform: template
    sensors:
      front_lock_battery:
        device_class: battery
        friendly_name: Front Lock Battery
        unit_of_measurement: "%"
        value_template: "{{ state_attr('lock.front_door', 'lock battery') | replace('%', '') }}"
```
