### DISCUSSION TITLE
Setting fan mode on thermostat with an automation

### DISCUSSION THREAD

**Discussion by Nickjgniklu** [SecKatie/ha-wyzeapi#461] [Q&A]
Is it possible to set the fan mode of the wyze thermostat with an automation. The only action I found was to change the heating/cooling mode. Was wondering if I can just edit the yaml for the action or something?

**Comment by Nickjgniklu** [comment]
I think this is working 
```
alias: turn fan on when upstairs hot
description: test
trigger:
  - type: temperature
    platform: device
    device_id: 9ac435f31d90132f6a3c9e79e4035b08
    entity_id: sensor.plant_sensor_4152_temperature
    domain: sensor
    above: 78
condition: []
action:
  - service: climate.set_fan_mode
    target:
      entity_id: climate.thermostat
    data:
      fan_mode: "on"
mode: single
```
